name: ankigpt
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0-126.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
